### ISSUE TITLE
scriptpath variable makes assumptions about no structure

### ISSUE THREAD

**Issue by ng-0** [meskarune/i3lock-fancy#83] opened 2017-05-26 11:11 UTC
```
# get path where the script is located to find the lock icon
scriptpath=$(readlink -f -- "$0")
scriptpath=${scriptpath%/*}
```
…
```
 icon="$scriptpath/icons/lockdark.png"
```

This assumption fails when the script is located in an immutable location (/gnu/store/ in our case).
Executed directly from its root, you get this failure:
```
user@abyayala /gnu/store/qvlin3pmsysxqi4nkag6ibjv09l1dwk1-i3lock-fancy-0.2/bin$ ./i3lock-fancy 
convert: unable to open image `/gnu/store/qvlin3pmsysxqi4nkag6ibjv09l1dwk1-i3lock-fancy-0.2/bin/icons/lockdark.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert: unable to open file `/gnu/store/qvlin3pmsysxqi4nkag6ibjv09l1dwk1-i3lock-fancy-0.2/bin/icons/lockdark.png' @ error/png.c/ReadPNGImage/4046.
convert: no images defined `/tmp/tmp.j96mGODH5q.png' @ error/convert.c/ConvertImageCommand/3258.
```
This error assumes that you have installed i3lock-fancy in this structure:

```
user@abyayala /gnu/store/qvlin3pmsysxqi4nkag6ibjv09l1dwk1-i3lock-fancy-0.2/bin$ tree ..
..
├── bin
│   └── i3lock-fancy
└── share
    └── i3lock-fancy
        └── icons
            ├── circlelockcleardark.png
            ├── circlelockclear.png
            ├── circlelockdark.png
            ├── circlelock.png
            ├── lockdark.png
            ├── lock.png
            ├── tokendark.png
            └── token.png
```
I am going to patch this by hand again, but it makes sense to not assume relative paths. Instead just have
variable iconpath=/usr/share/i3lock-fancy or something.
I have to substitute the /usr/ anyway.

What do you think?

**Comment by EmilePouget** [comment] 2017-05-26 11:19
The "problem" was that you renamed some variables, which made me detect this behavior.

Right now my install of i3lock-fancy looks like this (excerpt):

```
    (arguments
     `(#:tests? #f ;No tests included
       #:phases
       (modify-phases %standard-phases
         (replace 'configure
           (lambda* (#:key inputs outputs #:allow-other-keys)
             (let* ((out (assoc-ref outputs "out"))
                    (icons (string-append out "/share/i3lock-fancy/icons/"))
                    (i3lock (string-append (assoc-ref inputs "i3lock-color")
                                           "/bin/i3lock"))
                    (wmctrl (string-append (assoc-ref inputs "wmctrl")
                                           "/bin/wmctrl"))
                    (mconvert (string-append (assoc-ref inputs "imagemagick")
                                             "/bin/convert"))
                    (mimport (string-append (assoc-ref inputs "imagemagick")
                                            "/bin/import"))
                    (awk (string-append (assoc-ref inputs "gawk")
                                        "/bin/gawk")))

               (substitute* "lock"
                 (("if ! i3lock") (string-append "if ! " i3lock))
                 (("i3lock -n") (string-append i3lock " -n"))
                 (("$(which wmctrl)") wmctrl)
                 (("convert") mconvert)
                 (("shot=\\(import") (string-append "shot=\(" mimport))
                 (("awk -F") (string-append awk " -F"))
                 ((" awk") awk)
                 (("\\$scriptpath/icons/") icons))
               #t)))
         (delete 'build)
         (replace 'install
           (lambda* (#:key inputs outputs #:allow-other-keys)
             (let* ((out (assoc-ref outputs "out"))
                    (bin (string-append out "/bin"))
                    (icons (string-append out "/share/i3lock-fancy/icons/")))

               (install-file "lock" bin)
               (rename-file (string-append bin "/lock")
                            (string-append bin "/i3lock-fancy"))
               (copy-recursively "icons" icons)
               #t))))))
    (native-inputs
     `(("imagemagick" ,imagemagick)
       ("i3lock-color" ,i3lock-color)
       ("wmctrl" ,wmctrl)
       ("gawk" ,gawk)))
```

**Comment by EmilePouget** [comment] 2017-05-26 11:37
Actually this behavior is correct and unless my current error isn't PAM related this doesn't need a change.
Setting the right scriptpath helps.

**Comment by AladW** [comment] 2017-06-29 09:31
Duplicate of #81

**Closed by AladW** 2017-06-29 09:31 UTC
