### ISSUE TITLE
Using i3lock-fancy prevents system from suspending

### ISSUE THREAD

**Issue by leggettc13** [meskarune/i3lock-fancy#79] opened 2017-05-18 06:27 UTC
I have a command that will lock the screen and then suspend the system so the lock screen is shown when the system resumes. However, when using it with i3lock-fancy instead, it will lock the screen and the suspend will not occur. It will then suspend after I unlock the screen.
```
set $Locker i3lock-fancy

set $mode_system System (l) lock, (e) logout, (s) suspend, (h) hibernate, (r) reboot, (Shift+s) shutdown
mode "$mode_system" {
    bindsym l exec --no-startup-id $Locker, mode "default"
    bindsym e exec --no-startup-id i3-msg exit, mode "default"
    bindsym s exec --no-startup-id $Locker && systemctl suspend, mode "default"
    bindsym h exec --no-startup-id $Locker && systemctl hibernate, mode "default"
    bindsym r exec --no-startup-id systemctl reboot, mode "default"
    bindsym Shift+s exec --no-startup-id systemctl poweroff -i, mode "default"

    # back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+Pause mode "$mode_system"
```
This code works just fine with regular i3lock but not with i3lock-fancy. Is there something I need to do differently with it or is there some limitation or bug that I'm running into?

**Comment by AladW** [comment] 2017-05-18 09:09
Duplicate of #60 #66 #67 #77 

Just edit the script with an editor of choice and remove the `-n` parameter.

**Closed by AladW** 2017-05-18 09:09 UTC
Labels: duplicate
