### ISSUE TITLE
Blur effect flickering on dual monitors

### ISSUE THREAD

**Issue by jrlil** [meskarune/i3lock-fancy#58] opened 2016-10-27 13:10 UTC
When the command below is submitted, the script blurs the screen but then the unblurred version of the screen appears every few seconds. This only happens when two monitors are in use but not when only one is connected. I noticed similar behaviour with _i3lock-blur_. Does the _i3lock-fancy_ not support multiple monitors or is this a bug?

```
i3lock -u -f
```

**Comment by chrjguill** [comment] 2016-10-27 16:22
This sounds like a problem with [my i3lock fork](https://github.com/chrjguill/i3lock-color). I use dual monitors and don't experience this; could you provide some more details?

**Comment by jrlil** [comment] 2016-11-03 09:40
This flickering only occurs with the blur effect and there are no such problems when simply *i3lock* is ran.

Here's what fills up my terminal when I run *i3lock -f --debug*:

```
[i3lock-debug] device = 3
[i3lock-debug] found Xinerama screen: 1920 x 1200 at 1080 x 0
[i3lock-debug] found Xinerama screen: 1080 x 1920 at 0 x 0
scaling factor = 19.200000	radius = 9	sigma = 9.600000
[i3lock-debug] device = 3
X11 Error received! sequence 0x144, error_code = 8, major = 0x3e, minor = 0x0
X11 Error received! sequence 0x145, error_code = 8, major = 0x3e, minor = 0x0
X11 Error received! sequence 0x146, error_code = 8, major = 0x3e, minor = 0x0
X11 Error received! sequence 0x147, error_code = 8, major = 0x3e, minor = 0x0
X11 Error received! sequence 0x148, error_code = 8, major = 0x3e, minor = 0x0
X11 Error received! sequence 0x149, error_code = 8, major = 0x3e, minor = 0x0
...
```

Here's my xrandr output:

```
Screen 0: minimum 8 x 8, current 3000 x 1920, maximum 32767 x 32767
LVDS1 connected (normal left inverted right x axis y axis)
   1600x900      60.00 +
   1368x768      60.00  
   1280x720      60.00  
   1024x768      60.00  
   1024x576      60.00  
   960x540       60.00  
   800x600       60.32    56.25  
   864x486       60.00  
   800x450       60.00  
   640x480       59.94  
   720x405       60.00  
   640x360       60.00  
DP1 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 disconnected (normal left inverted right x axis y axis)
HDMI1 disconnected (normal left inverted right x axis y axis)
HDMI2 connected 1080x1920+0+0 left (normal left inverted right x axis y axis) 510mm x 290mm
   1920x1080     60.00*+
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.90  
   1280x720      60.00  
   1024x768      60.00  
   800x600       60.32  
   640x480       59.94  
   720x400       70.08  
HDMI3 disconnected (normal left inverted right x axis y axis)
VGA1 connected 1920x1200+1080+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
   1600x1200     60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
   720x400       70.08  
VIRTUAL1 disconnected (normal left inverted right x axis y axis)
```

**Comment by chrjguill** [comment] 2016-11-03 13:10
I'll look into the X11 errors when I can. What happens when you just lock with any image set as the background?

**Comment by jrlil** [comment] 2016-11-03 13:24
Setting a .png image as background works fine. I'm using a docked laptop with 2 monitors connected via the dock (this uncommon setup likely has something to do with my problem).

**Comment by chrjguill** [comment] 2016-11-03 15:19
That's interesting and likely part of the problem. xrandr is reporting that the current resolution is 3000x3000, but looking at the numbers - shouldn't it be `1600 + 1080 + 1920 -> 4600` by 1920?

Not entirely sure what up and I haven't had issues with dual/triple monitors, so I can't really reproduce, but I'll try and see if there's anything I can do. 

If you go look at the [blur](https://github.com/chrjguill/i3lock-color/tree/blur) branch of my fork and try its `-B` option, does it still occur then? (or [seb's fast-blur](sebastian-frysztak/i3lock-color/tree/fast-blur), since it should be the same)

**Comment by AladW** [comment] 2016-11-03 20:31
The command in the original post is `i3lock`, not the script in this repository. Are we at fault here, or is this specific to the fork used?

**Comment by chrjguill** [comment] 2016-11-04 01:59
Pretty sure it's not even specific to the fork, but just a weird problem with his setup.

@jrlil can you try setting the blurred background image with regular i3lock to see if it's one of my patches that introduced it? If it produces on vanilla i3lock it might be worth filing an upstream issue on.

**Comment by jrlil** [comment] 2016-11-05 18:01
I installed regular i3lock and after replacing it with *i3lock-fancy-git* from AUR, the `-f` option does not exist anymore. The *i3lock-color* does not seem to have a blur option so I couldn't test that. I also figured out that running `i3lock-fancy` works fine, the suggestion to run `lock` in the readme was a bit misleading since this command doesn't do anything for me in my Arch system.  

So I'm not sure what the problem was but it's gone now and it might have not been *i3lock-fancy*.

**Comment by chrjguill** [comment] 2016-11-05 18:51
* i3lock-fancy-git doesn't replace or provide i3lock, so it doesn't replace i3lock
* i3lock-color has blurring in one of the linked branches; you'd need to checkout to that branch and then `make` to be able to blur
* That is a good point about how on arch the provided binary is different from the readme. I can't actually think of anything that that'd override, but it's probably best to leave it as it is.

**Comment by AladW** [comment] 2016-11-06 14:08
Closing then. Thanks.

**Closed by AladW** 2016-11-06 14:08 UTC
Labels: question
